/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as ManagersIndexRouteImport } from './routes/managers/index'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as TeachersNewRouteImport } from './routes/teachers/new'
import { Route as ManagersNewRouteImport } from './routes/managers/new'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as TeachersTeacherIdEditRouteImport } from './routes/teachers/$teacherId/edit'
import { Route as ManagersManagerIdEditRouteImport } from './routes/managers/$managerId.edit'
import { Route as FamiliesParentsNewRouteImport } from './routes/families/parents/new'
import { Route as FamiliesChildrenNewRouteImport } from './routes/families/children/new'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiCronSecondPingRouteImport } from './routes/api.cron.second-ping'
import { Route as ApiCronNineAmCheckRouteImport } from './routes/api.cron.nine-am-check'
import { Route as ApiCronMorningMessagesRouteImport } from './routes/api.cron.morning-messages'
import { Route as FamiliesParentsParentIdEditRouteImport } from './routes/families/parents/$parentId/edit'
import { Route as FamiliesChildrenChildIdEditRouteImport } from './routes/families/children/$childId/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersIndexRoute = ManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersNewRoute = TeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersNewRoute = ManagersNewRouteImport.update({
  id: '/managers/new',
  path: '/managers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdEditRoute = TeachersTeacherIdEditRouteImport.update({
  id: '/teachers/$teacherId/edit',
  path: '/teachers/$teacherId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersManagerIdEditRoute = ManagersManagerIdEditRouteImport.update({
  id: '/managers/$managerId/edit',
  path: '/managers/$managerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesParentsNewRoute = FamiliesParentsNewRouteImport.update({
  id: '/families/parents/new',
  path: '/families/parents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesChildrenNewRoute = FamiliesChildrenNewRouteImport.update({
  id: '/families/children/new',
  path: '/families/children/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSecondPingRoute = ApiCronSecondPingRouteImport.update({
  id: '/api/cron/second-ping',
  path: '/api/cron/second-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNineAmCheckRoute = ApiCronNineAmCheckRouteImport.update({
  id: '/api/cron/nine-am-check',
  path: '/api/cron/nine-am-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMorningMessagesRoute = ApiCronMorningMessagesRouteImport.update({
  id: '/api/cron/morning-messages',
  path: '/api/cron/morning-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesParentsParentIdEditRoute =
  FamiliesParentsParentIdEditRouteImport.update({
    id: '/families/parents/$parentId/edit',
    path: '/families/parents/$parentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FamiliesChildrenChildIdEditRoute =
  FamiliesChildrenChildIdEditRouteImport.update({
    id: '/families/children/$childId/edit',
    path: '/families/children/$childId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/managers/new': typeof ManagersNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/families/': typeof FamiliesIndexRoute
  '/managers/': typeof ManagersIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/api/cron/morning-messages': typeof ApiCronMorningMessagesRoute
  '/api/cron/nine-am-check': typeof ApiCronNineAmCheckRoute
  '/api/cron/second-ping': typeof ApiCronSecondPingRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/families/children/new': typeof FamiliesChildrenNewRoute
  '/families/parents/new': typeof FamiliesParentsNewRoute
  '/managers/$managerId/edit': typeof ManagersManagerIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/families/children/$childId/edit': typeof FamiliesChildrenChildIdEditRoute
  '/families/parents/$parentId/edit': typeof FamiliesParentsParentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/managers/new': typeof ManagersNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/families': typeof FamiliesIndexRoute
  '/managers': typeof ManagersIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/api/cron/morning-messages': typeof ApiCronMorningMessagesRoute
  '/api/cron/nine-am-check': typeof ApiCronNineAmCheckRoute
  '/api/cron/second-ping': typeof ApiCronSecondPingRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/families/children/new': typeof FamiliesChildrenNewRoute
  '/families/parents/new': typeof FamiliesParentsNewRoute
  '/managers/$managerId/edit': typeof ManagersManagerIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/families/children/$childId/edit': typeof FamiliesChildrenChildIdEditRoute
  '/families/parents/$parentId/edit': typeof FamiliesParentsParentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/attendance': typeof AttendanceRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/managers/new': typeof ManagersNewRoute
  '/teachers/new': typeof TeachersNewRoute
  '/families/': typeof FamiliesIndexRoute
  '/managers/': typeof ManagersIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/api/cron/morning-messages': typeof ApiCronMorningMessagesRoute
  '/api/cron/nine-am-check': typeof ApiCronNineAmCheckRoute
  '/api/cron/second-ping': typeof ApiCronSecondPingRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/families/children/new': typeof FamiliesChildrenNewRoute
  '/families/parents/new': typeof FamiliesParentsNewRoute
  '/managers/$managerId/edit': typeof ManagersManagerIdEditRoute
  '/teachers/$teacherId/edit': typeof TeachersTeacherIdEditRoute
  '/families/children/$childId/edit': typeof FamiliesChildrenChildIdEditRoute
  '/families/parents/$parentId/edit': typeof FamiliesParentsParentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/login'
    | '/manager'
    | '/settings'
    | '/auth/callback'
    | '/managers/new'
    | '/teachers/new'
    | '/families/'
    | '/managers/'
    | '/teachers/'
    | '/api/cron/morning-messages'
    | '/api/cron/nine-am-check'
    | '/api/cron/second-ping'
    | '/api/whatsapp/webhook'
    | '/families/children/new'
    | '/families/parents/new'
    | '/managers/$managerId/edit'
    | '/teachers/$teacherId/edit'
    | '/families/children/$childId/edit'
    | '/families/parents/$parentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/attendance'
    | '/login'
    | '/manager'
    | '/settings'
    | '/auth/callback'
    | '/managers/new'
    | '/teachers/new'
    | '/families'
    | '/managers'
    | '/teachers'
    | '/api/cron/morning-messages'
    | '/api/cron/nine-am-check'
    | '/api/cron/second-ping'
    | '/api/whatsapp/webhook'
    | '/families/children/new'
    | '/families/parents/new'
    | '/managers/$managerId/edit'
    | '/teachers/$teacherId/edit'
    | '/families/children/$childId/edit'
    | '/families/parents/$parentId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendance'
    | '/login'
    | '/manager'
    | '/settings'
    | '/auth/callback'
    | '/managers/new'
    | '/teachers/new'
    | '/families/'
    | '/managers/'
    | '/teachers/'
    | '/api/cron/morning-messages'
    | '/api/cron/nine-am-check'
    | '/api/cron/second-ping'
    | '/api/whatsapp/webhook'
    | '/families/children/new'
    | '/families/parents/new'
    | '/managers/$managerId/edit'
    | '/teachers/$teacherId/edit'
    | '/families/children/$childId/edit'
    | '/families/parents/$parentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AttendanceRoute: typeof AttendanceRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ManagersNewRoute: typeof ManagersNewRoute
  TeachersNewRoute: typeof TeachersNewRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  ManagersIndexRoute: typeof ManagersIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  ApiCronMorningMessagesRoute: typeof ApiCronMorningMessagesRoute
  ApiCronNineAmCheckRoute: typeof ApiCronNineAmCheckRoute
  ApiCronSecondPingRoute: typeof ApiCronSecondPingRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  FamiliesChildrenNewRoute: typeof FamiliesChildrenNewRoute
  FamiliesParentsNewRoute: typeof FamiliesParentsNewRoute
  ManagersManagerIdEditRoute: typeof ManagersManagerIdEditRoute
  TeachersTeacherIdEditRoute: typeof TeachersTeacherIdEditRoute
  FamiliesChildrenChildIdEditRoute: typeof FamiliesChildrenChildIdEditRoute
  FamiliesParentsParentIdEditRoute: typeof FamiliesParentsParentIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/': {
      id: '/managers/'
      path: '/managers'
      fullPath: '/managers/'
      preLoaderRoute: typeof ManagersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/new': {
      id: '/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof TeachersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/new': {
      id: '/managers/new'
      path: '/managers/new'
      fullPath: '/managers/new'
      preLoaderRoute: typeof ManagersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId/edit': {
      id: '/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/teachers/$teacherId/edit'
      preLoaderRoute: typeof TeachersTeacherIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers/$managerId/edit': {
      id: '/managers/$managerId/edit'
      path: '/managers/$managerId/edit'
      fullPath: '/managers/$managerId/edit'
      preLoaderRoute: typeof ManagersManagerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/parents/new': {
      id: '/families/parents/new'
      path: '/families/parents/new'
      fullPath: '/families/parents/new'
      preLoaderRoute: typeof FamiliesParentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/children/new': {
      id: '/families/children/new'
      path: '/families/children/new'
      fullPath: '/families/children/new'
      preLoaderRoute: typeof FamiliesChildrenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/second-ping': {
      id: '/api/cron/second-ping'
      path: '/api/cron/second-ping'
      fullPath: '/api/cron/second-ping'
      preLoaderRoute: typeof ApiCronSecondPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/nine-am-check': {
      id: '/api/cron/nine-am-check'
      path: '/api/cron/nine-am-check'
      fullPath: '/api/cron/nine-am-check'
      preLoaderRoute: typeof ApiCronNineAmCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/morning-messages': {
      id: '/api/cron/morning-messages'
      path: '/api/cron/morning-messages'
      fullPath: '/api/cron/morning-messages'
      preLoaderRoute: typeof ApiCronMorningMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/parents/$parentId/edit': {
      id: '/families/parents/$parentId/edit'
      path: '/families/parents/$parentId/edit'
      fullPath: '/families/parents/$parentId/edit'
      preLoaderRoute: typeof FamiliesParentsParentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/children/$childId/edit': {
      id: '/families/children/$childId/edit'
      path: '/families/children/$childId/edit'
      fullPath: '/families/children/$childId/edit'
      preLoaderRoute: typeof FamiliesChildrenChildIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AttendanceRoute: AttendanceRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ManagersNewRoute: ManagersNewRoute,
  TeachersNewRoute: TeachersNewRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  ManagersIndexRoute: ManagersIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  ApiCronMorningMessagesRoute: ApiCronMorningMessagesRoute,
  ApiCronNineAmCheckRoute: ApiCronNineAmCheckRoute,
  ApiCronSecondPingRoute: ApiCronSecondPingRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  FamiliesChildrenNewRoute: FamiliesChildrenNewRoute,
  FamiliesParentsNewRoute: FamiliesParentsNewRoute,
  ManagersManagerIdEditRoute: ManagersManagerIdEditRoute,
  TeachersTeacherIdEditRoute: TeachersTeacherIdEditRoute,
  FamiliesChildrenChildIdEditRoute: FamiliesChildrenChildIdEditRoute,
  FamiliesParentsParentIdEditRoute: FamiliesParentsParentIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
